version: '3'
services:
  my-notebook:
    ports:
      - 9999:9999 # ports to open in container for jupyter notebook
    build: . # location of Dockerfile
    # volumes:
    #   - /path/on/host:/path/in/container